-- how to find employees information of who is making highest salary in the company

--GET ME THE HIGHEST SALARY
SELECT MAX(SALARY)
FROM EMPLOYEES;

--HIGHEST SALARY EMPLOYEE INFORMATION
SELECT *
FROM EMPLOYEES
WHERE SALARY = 240000;

--SUB QUERY SOLUTION IN ONE SHOT
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

--FINDING SECOND HIGHEST SALARY
--GET HIGHEST SALARY FIRST
SELECT MAX(SALARY)
FROM EMPLOYEES;

--HIGHEST AFTER 24K
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < 24000;

--ONE SHOT COMBINING TO QUERIES
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES);

--EMPLOYEE INFORMATION OF WHO IS MAKING SECOND HIGHEST SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY= (SELECT MAX(SALARY)FROM EMPLOYEES WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES));

SELECT * FROM EMPLOYEES ORDER BY SALARY DESC ;

SELECT * FROM EMPLOYEES WHERE ROWNUM < 11;

--LIST THE EMPLOYESS WHO IS MAKING TOP 10 SALARY
--GET THE FIRST 10 PEOPLE THEN ORDER THEM HIGH TO LOW BASED ON SALARY
SELECT * FROM EMPLOYEES WHERE ROWNUM <11 ORDER BY SALARY DESC ;

--ORDER ALL EMPLOYEES BASED ON SALARY HIGH TO LOW DISPLAY ONLY FIRST 10 RESULT
SELECT * FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM <11;



