--LIST SALARY HIGH TO LOW WITHOUT DUPLICATE VALUES
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;


--find the highest 14th salary(REMOVING DUPLICATES VALUES)
SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC)
WHERE ROWNUM < 15;


--FIND EMPLOYEE INFO WHO IS MAKING 14TH HIGHEST SALARY(with duplicates)
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM (SELECT * FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM < 15);

--FIND EMPLOYEE INFO WHO IS MAKING 14TH HIGHEST SALARY(withOUT duplicates)
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM (SELECT DISTINCT SALARY FROM EMPLOYEES ORDER BY SALARY DESC) WHERE ROWNUM < 15);