SELECT * FROM EMPLOYEES ;
--READS ALL COLUMN FROM EMPLOYEES TABLE

SELECT * FROM DEPARTMENTS ;
--READS ALL COLUMN FROM DEPARTMENTS TABLE

SELECT FIRST_NAME FROM EMPLOYEES ;
--GET ONLY FIRSTNAME FROM EMPLOYEES TABLE

--DISPLAY CITY NAMES
SELECT CITY FROM LOCATIONS ;

--GET ME FIRSTNAME,LASTNAME AND SALARY
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES ;

--get me street adress and postal code
SELECT STREET_ADDRESS,POSTAL_CODE FROM LOCATIONS ;

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES ;
--removes duplicated


