-- get me ALL info who is working as IT_PROG or SA_REP
SELECT *
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'SA_REP');

--how many employee working as IT_PROG or SA_REP
SELECT COUNT(*)
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'SA_REP');

----how many employee making more than 8000
SELECT COUNT(*)
FROM EMPLOYEES
WHERE SALARY > 8000;

--HOW MANY UNIQUE NAMES WE HAVE
SELECT COUNT(DISTINCT FIRST_NAME)
FROM EMPLOYEES;

--GET ME ALL EMPLOYEES INFORMATION BASED ON WHO IS MAKING MORE SALARY TO LOW SALARY
SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;

--DESC 9-0 Z-A
--ASC 0-9 A-Z

--GET ME ALL EMP INFO ORDER BY ALPHABETHICAL BASED ON FIRSTNAME
SELECT *
FROM EMPLOYEES
ORDER BY FIRST_NAME ASC;

--NOTE: default order type is asc if you dont specify after column name


--get me all employees whose first name starts with C
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'E%';

--GET ME 5 LETTER FIST NAME WHERE THE MIDDLE CHAR IS z
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__z__';

--GET ME FIST NAME WHERE SECOND CHAR IS u
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_u%';

--FIND MINIMIUM SALARY
SELECT min(SALARY)
FROM EMPLOYEES;

--FIND MAXIMIUM SALARY
SELECT max(SALARY)
FROM EMPLOYEES;

--FIND AVARAGE SALARY
SELECT avg(SALARY)
FROM EMPLOYEES;

--ROUND
SELECT ROUND(avg(SALARY))
FROM EMPLOYEES;

--ROUND (decimal part)
SELECT ROUND(avg(SALARY),3)
FROM EMPLOYEES;

SELECT sum(SALARY) FROM EMPLOYEES;
